# Change these first
owner: P3D-Legacy # Your GitHub organization or username, where this repository lives
repo: status.pokemon3d.net # The name of this repository

assignees: DanielRTRD

sites:
  - name: pokemon3d.net
    url: https://pokemon3d.net
  - name: karp.pokemon3d.net
    check: "tcp-ping"
    url: karp.pokemon3d.net
    port: 15124

status-website:
  name: "P3D-Legacy - Status"
  logoUrl: https://pokemon3d.net/img/pokemon3d_logo_sm.png
  cname: status.pokemon3d.net
  navbar:
    - title: Status
      href: /
    - title: pokemon3d.net
      href: https://pokemon3d.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
