owner: P3D-Legacy
repo: status.pokemon3d.net

assignees: DanielRTRD

sites:
  - name: pokemon3d.net
    url: https://pokemon3d.net
    expectedStatusCodes:
      - 200
  - name: Wiki
    url: https://wiki.pokemon3d.net
    expectedStatusCodes:
      - 200
  - name: Forum
    url: https://forum.pokemon3d.net
    expectedStatusCodes:
      - 200
  - name: Game Server - karp.pokemon3d.net
    check: "tcp-ping"
    url: karp.pokemon3d.net
    port: 15124
  - name: GameJolt API
    url: https://api.gamejolt.com/api/game/v1_2/time/?game_id=$GAME_ID
    method: GET
    headers:
    - "Content-Type: application/json"

status-website:
  name: "P3D-Legacy - Status"
  logoUrl: https://pokemon3d.net/img/pokemon3d_logo_sm.png
  cname: status.pokemon3d.net
  navbar:
    - title: Status
      href: /
    - title: pokemon3d.net
      href: https://pokemon3d.net
